/*
  Auto-generated by Spline
*/

import dynamic from "next/dynamic";

const Spline = dynamic(() => import("@splinetool/react-spline"), {
  ssr: false,
});

export default function App() {
  return (
    <Spline scene="https://prod.spline.design/3ioTEE5tnYDlyNJV/scene.splinecode" />
  );
}
